### ISSUE TITLE
activity not found

### ISSUE THREAD

**Issue by ZathKipp** [scheidan/RuminatoR#1]
Dear ScheidAn,

thank you very much for the code.
I tried to work with it. As I am not that good in R, I am not sure, if I did a mistake or if something in the code does not work.
I did the following:
 Uploading training file: Tier02Classifier
 Uploading the file which should be analysied: Tier02Data

What I changed in the code is in bold:

## 1) train classifier

rf.classifier <- train(**data=****Tier02Classifier**,
                       min.amplitude=30, min.dt=6)

## 2) apply classifier to new data

dat.class <- classify(rf.classifier, **newdata = Tier02Data**,
                      max.dt.peak = 30, min.n.peaks = 10)

head(dat.class)

Here I only get NA for "activity.predicted"

                     time pressure activity.predicted
1        07.03.2020 09:01   1077.3               <NA>
2 07.03.2020 09:01:07.018   1076.8               <NA>
3        07.03.2020 09:01   1077.0               <NA>
4        07.03.2020 09:01   1077.7               <NA>
5        07.03.2020 09:01   1077.4               <NA>
6        07.03.2020 09:01   1076.9               <NA>

table(dat.class$activity)
However, here I get results, so maybe the first rows are no behaviour, which could be classified.
   feeding ruminating   suckling 
     34743      12803      38904 

 ## color line
> ggplot(dat.class, aes(x=time, y=pressure, color=activity)) +
+   geom_path(aes(group=1))
**Fehler in FUN(X[[i]], ...) : Objekt 'activity' nicht gefunden**

Then I changed the code (in bold): activity.predicted instead of activity
## color line
ggplot(dat.class, aes(x=time, y=pressure, color=**activity.predicted**)) +
  geom_path(aes(group=1))

## color background
ggplot(dat.class) +
  ## background
  geom_rect(aes(NULL, NULL,
                xmin=time-0.5, xmax=time+0.5,
                ymin=-Inf, ymax=Inf,
                fill=**activity.predicted**)) +
  ## add pressure
  geom_path(aes(x=time, y=pressure))

Now I get another error:
**Fehler in time - 0.5 : nicht-numerisches Argument für binären Operator**

When I ask str(dat.class), I get the following:
> str(dat.class)
'data.frame':	361503 obs. of  3 variables:
 $ time              : chr  "07.03.2020 09:01" "07.03.2020 09:01:07.018" "07.03.2020 09:01" "07.03.2020 09:01" ...
 $ pressure          : num  1077 1077 1077 1078 1077 ...
 $ activity.predicted: Factor w/ 3 levels "feeding","ruminating",..: NA NA NA NA NA NA NA NA NA NA ...

Do you have an idea what went wrong?
Thanks a lot
Kathi

**Comment by scheidan** [comment]
I think we have two errors here:

1. `data.class$activity` should be `data.class$activity.predicted` This was wrong in the Readme example and is changed now. 
2. It's normal to that the first and last rows are NA. We need a data of a certain length to make the prediction.
3. The last error is probably because you did not convert `dat.class$time` in a time class (it's still a character string). You could try something like: `data.class$time <- as.POSIXct(strptime(data.class$time, format="%d.%m.%Y %H:%M:%OS"))` or 
```R
library(lubridate)
data.class$time <- parse_date_time(data.class$time, orders=c("d.m.y H:M:OS", "d.m.y H:M:S"))
```

I hope that works now :)
